--criando tabelas no mysql

CREATE DATABASE EVALUATION;

CREATE TABLE CATEGORY(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (100) NOT NULL,
     PRIMARY KEY (id)
);

CREATE TABLE PRODUCT(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(100, 2) NOT NULL,
    WEIGHT DECIMAL(100, 2) NOT NULL,
    CATEGORY_ID INT,
    PRIMARY KEY (id),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'João'), (2, 'Maria');